version: '3.5'

services:

  db:
    volumes:
      - /project/.sqldata:/var/lib/mysql
    networks:
      - internal
    labels:
      - traefik.enable=false

  ruilwinkelvaals.webapp:
    image: zuydteamf/project-ruilwinkel-vaals:latest
    networks:
      - web
      - internal
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.backend=ruilwinkelvaals.webapp
      - traefik.frontend.rule=Host:zuydest.nl
      - traefik.port=80

  reverse-proxy:
    image: traefik:1.7.9
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/traefik/traefik.toml:/traefik.toml
      - /usr/local/traefik/acme.json:/acme.json
    networks:
      - web

networks:
  web:
    external: true
  internal:
    external: false
