name: Build & Tests

on:
  push:
    branches:
    - development
    
  pull_request:
    branches: 
    - development

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Start SQL Server
      run: |
        docker run -d -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=${{ secrets.DB_PASSWORD }}' -e 'MSSQL_PID=Express' -p 1433:1433 -d mcr.microsoft.com/mssql/server:latest
        
    - name: Wait for the SQL Server to Init 🙃
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'
        
    - name: Restore dependencies
      run: dotnet restore RuilwinkelVaals.sln
      
    - name: Build Project
      run: dotnet build --no-restore RuilwinkelVaals.sln
      
    - name: Run Tests
      env: 
        ConnectionStrings__DefaultConnection: Server=localhost;Database=TestDB;User Id=sa;Password=${{secrets.DB_PASSWORD}};
      run: dotnet test --no-build --verbosity normal RuilwinkelVaals.sln
