name: Sonar Scan
on:
  push:
    branches:
      - development
jobs:
  validate-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          # Disabling shallow clone is recommended for improving relevancy of sonarqube reporting
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: dotnet restore RuilwinkelVaals.sln

      - name: Sonarqube Begin
        run: | 
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /o:"zuyd-team-f" /k:"Zuyd-Team-F_project-ruilwinkel-vaals" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /s:$GITHUB_WORKSPACE/SonarQube.Analysis.xml

      - name: Build
        run: dotnet build RuilwinkelVaals.sln

      - name: Test with the dotnet CLI
        run: dotnet test --settings coverlet.runsettings --logger:trx RuilwinkelVaals.sln
        env:
          ASPNETCORE_ENVIRONMENT: Development

      - name: Sonarqube end
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
